# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "s3-tf-state-tg-juan"
    dynamodb_table = "dynamo-terraform-lock"
    encrypt        = true
    key            = "vpc-ec2/terraform.tfstate"
    region         = "us-east-2"
  }
}
